### ISSUE TITLE
Bug in setting of autoflush timeout

### ISSUE THREAD

**Issue by vaclavbartos** [CESNET/Nemea-Framework#105]
I reviwed the code and I think there should be `timeout_fixed`, not `datatimeout_fixed` on the following line:
https://github.com/CESNET/Nemea-Framework/blob/0ac1029a78da7b6273d8d50db49855c135653769/libtrap/src/trap.c#L2075

**Comment by janskto1** [comment]
Confirmed and solved in https://github.com/CESNET/Nemea-Framework/pull/104.
Thanks for reporting the bug.
