### ISSUE TITLE
Invalid help string for createMessage function in pytrap.

### ISSUE THREAD

**Issue by achieveOrbit** [CESNET/Nemea-Framework#169]
The help string for the `createMessage` function in `pytrapmodule.c` seems to incorrectly state that the maximum size for a message containing variable length fields is 100.

https://github.com/CESNET/Nemea-Framework/blob/c372105d81bdc4556a703e1f8f9b31599148019e/pytrap/src/pytrapmodule.c#L617

However, when I was using this module I had no issue making messages of size 500, 700, 1000, and 5000. This leads to me to believe the docstring is outdated. I would create a pull request but I don't know what the correct value in the docstring should be, or _if_ it should really even specify a maximum size.

Hope this helps,

Lukáš

**Comment by cejkato2** [comment]
Well, I agree the description is not clear enough. To explain this: a developer gives size of memory as an argument and he/she must not write more data than the given size...
