### ISSUE TITLE
Fix API of ip_prefix_search

### ISSUE THREAD

**Issue by cejkato2** [CESNET/Nemea-Framework#23]
Revisit https://github.com/CESNET/Nemea-Framework/blob/ip_prefix_search/common/include/ip_prefix_search.h

Public API - that means content of this header file MUST contain only a minimal set of functions that is necessary for usage. Remove all functions that are used just internally.

Remove included header files that are not necessary for users. E.g. you have included signal.h, stdio.h and others - these header files are probably not necessary to have in the public API.

Public API MUST have all public functions named with some common prefix (it should be logical) in order to recognize that they belong together. You can use ipps_ if you want.

Revisit https://github.com/CESNET/Nemea-Framework/blob/ip_prefix_search/common/ip_prefix_search/ip_prefix_search.c and mark all "private" (internally used) functions as static.

**Comment by plotenyondra** [comment]
Fix by commit:
https://github.com/CESNET/Nemea-Framework/pull/22/commits/1b783648b4c3dac8d436ced5e2a3ce7f43cd9bf8

private function were moved to internal header file
