### ISSUE TITLE
python3 support

### ISSUE THREAD

**Issue by cejkato2** [CESNET/Nemea-Framework#3]
We need to improve python wrapper code in `python/` in order to support python3.
Some work is already done in #2 in the CESNET/Nemea-Framework/python3 branch.
It should be tested using the python_example.py module.

**Comment by DarthJuri** [comment]
The optparse is deprecated module and should be replaced by the argparse module. I will try to do it.

**Comment by cejkato2** [comment]
Merged #4

**Comment by cejkato2** [comment]
Merged #5 
Thanks!

Should we open another issue for optparse?

Can we close this issue?

**Comment by DarthJuri** [comment]
After all, I think, it is not necessary to replace the optparse module by the argparse.

Yes, this issue can be closed.

**Comment by cejkato2** [comment]
Unfortunately, this must be reopened due to errors in the rest of project...

* import fails in unirec_generate_fields_files.py
  see e.g. https://travis-ci.org/CESNET/Nemea-Framework/builds/100101445
  I tried to fix that but globally, I was not successful...

* in python 2.6.6 (old scientific linux) python_example.py fails:
       SyntaxError: unqualified exec is not allowed in function
       'CreateTemplate' it contains a nested function with free variables

**Comment by cejkato2** [comment]
Current status: https://travis-ci.org/CESNET/Nemea-Framework/branches

**Comment by DarthJuri** [comment]
Hi, what's the point of the libtrap_multiclient.test test? I'm afraid it behaves kind of nondeterministic. Sometimes it passes but sometimes don't without respect to the commits.
Thanks

**Comment by cejkato2** [comment]
Hi. Unfortunately, I have also observed some failures of this test. Let me explain the purpose:
* At first `clients` (10 by default) are created - it is the `test_echo_reply_ctx` - a simple module that receives all incoming messages and checks the value in it (it should be a previous value + 1).
* One server is created `test_echo_ctx` - a simple module that sends messages that are being received by clients.
* After 3 seconds of messages transfer, all clients are restarted one by one and the test checks if other clients remain connected (they should not be influenced by disconnection of anyone).
* The server is stopped by `SIGINT`. That should lead to sending terminal message in order to stop all connected clients.
* If any client remains alive, the test fails, since some clients did not receive terminal message.

I have to check the output of this failed test... I know about this issue (that should be probably created as a separate issue here) and I hope I will be able to fix it soon.

**Comment by cejkato2** [comment]
Solved using https://github.com/CESNET/Nemea-Framework/tree/master/pytrap.
Old python wrapper in python/ is deprecated and will be deleted soon.
