### ISSUE TITLE
Higher port numbers allowed in libtrap tcp interface

### ISSUE THREAD

**Issue by jaroslavh** [CESNET/Nemea-Framework#60]
Try running for example ```flow_meter -i t:65570``` or ```flow_meter -i t:655701```. It allows you to run it and probably overflows, for port 65570 it was running on port 34 when listing netstat -l (it is not surprisingly 65570-65536).

**Comment by cejkato2** [comment]
Should we add a new test into `tests/`?
I have a new patch, when I check it, I'll push it into #59.

**Comment by cejkato2** [comment]
FYI, here is an output of my local changed libtrap:
```
tests$ ./test_echo -i t:70000 -n 66
NOTICE: ./test_echo [number]
number - size of data to send for testing
ERROR: Given port (70000) number is out of the allowed range (1-65535).
ERROR: Socket could not be opened on given port '70000'.
ERROR: Initialization of TCPIP output interface no. 0 failed.
ERROR in TRAP initialization
tests$ 
```

Is the error message clear?

**Comment by jaroslavh** [comment]
The error message is clear. We could add test, should be easy.
