### ISSUE TITLE
unirec/ipaddr_cpp.h: wrong copy constructor

### ISSUE THREAD

**Issue by jaroslavh** [CESNET/Nemea-Framework#62]
Piece commented in [unirec/ipaddr_cpp.h](https://github.com/CESNET/Nemea-Framework/blob/master/unirec/ipaddr_cpp.h#L23) as copy constructor is not one. Valid copy constructor is needed. This piece of code is used so far only here in [hoststats](https://github.com/CESNET/Nemea-Detectors/blob/master/hoststatsnemea/src/eventhandler.cpp).

**Comment by KrobotP** [comment]
Please consider removal of unirec/ipaddr_cpp.h as:
- the only usage I can see in [hoststats](https://github.com/CESNET/Nemea-Detectors/blob/master/hoststatsnemea/src/eventhandler.cpp) is printing of an IP address which can be accomplished using ip_to_str() function in [UniRec](https://github.com/CESNET/Nemea-Framework/blob/master/unirec/ipaddr.h),
- usage of IPaddr_cpp class seems dangerous as a programmer has to be careful about double-frees (bool variable "new_object" is not sufficient like this).

**Comment by cejkato2** [comment]
I agree with removal.
Others? @vaclavbartos @janskto1 @svepemar @havraji6 @ladislavmacoun  ...

**Comment by vaclavbartos** [comment]
It's not even used in any of our internal modules, so I also agree with removal.

**Comment by janskto1** [comment]
Since it is not used and it is dangerous to use, removal of the class seems as a reasonable thing to do.

**Comment by jaroslavh** [comment]
I have a fix prepared. I running ```make dist check``` on Framework and Detectors enough before creating pull requests?
