### ISSUE TITLE
libtrap: tls interface: check possible issues with TLS setup

### ISSUE THREAD

**Issue by jaroslavh** [CESNET/Nemea-Framework#84]
In setting up TLS connection between modules return values should be better checked for errors. Especially around https://github.com/CESNET/Nemea-Framework/blob/master/libtrap/src/ifc_tls.c#L1039

Also should check again if everything works as expected (and does not leak) since I have improved my openSSL knowledge since last year.

**Comment by cejkato2** [comment]
I guess this was solved by #85 which didn't referred this issue in commit message, right?

**Comment by cejkato2** [comment]
#85 solves #84

**Comment by jaroslavh** [comment]
Yes, forgot to mention it in the pullrequest.

**Comment by cejkato2** [comment]
Thanks @jaroslavh for improving TLS IFC!
