### ISSUE TITLE
report2idea ignores name from warden config file

### ISSUE THREAD

**Issue by thorgrin** [CESNET/Nemea-Framework#86]
The reporter name from warden config file is ignored by all report2idea modules. The reason is here:
https://github.com/CESNET/Nemea-Framework/blob/6b656539af9791407d4e322571afdf6df936c8c0/pycommon/report2idea.py#L159

The name of the reporter module (parameter --name) is used instead. It should either be documented, or the name from warden config should be used.

**Comment by cejkato2** [comment]
Ok, I'd prefer documentation.
But where would you look for it?
(=where we should write it down?)

**Comment by cejkato2** [comment]
Is there any warden-client config example in NEMEA* repositories?
Because such eyanple file shouldn't contain name at all...

**Comment by thorgrin** [comment]
Yes, all the report2idea modules in https://github.com/CESNET/Nemea-Modules/tree/c84a0c3e1e6300e9491bdd7f0a221fd30a113a93/report2idea have a sample `config.cfg` file.

I think that the readme at that directory should inform about using and configuring the report2idea modules and that the examples should be in their own per-module respective files.

Moreover, the https://nemea.liberouter.org/reporting/ might say something about the warden configuration file as well as part of the warden action documentation.

**Comment by cejkato2** [comment]
Commit a24962df0 removes "name" from cfg files.
